/**
 * seal-keygen.ts — generate the operator's Sui keypair for Seal (SUI_SEAL_KEYPAIR).
 *
 * SECURITY: prints ONLY the public Sui address. The secret (suiprivkey…) is written
 * to ./seal-wallet.key (gitignored via *.key) and NEVER echoed to stdout, so it can't
 * leak into logs or a terminal transcript. Move it into .env yourself:
 *
 *   bun run apps/operator/scripts/seal-keygen.ts
 *   # then copy the SUI_SEAL_KEYPAIR line from seal-wallet.key into .env
 *
 * Idempotent guard: refuses to overwrite an existing seal-wallet.key.
 */
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { writeFileSync, existsSync, chmodSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(process.cwd(), "seal-wallet.key");

if (existsSync(OUT)) {
  console.error(`[seal-keygen] ${OUT} already exists — refusing to overwrite.`);
  console.error("[seal-keygen] delete it first if you really want a fresh key (you'd lose access to any funds on the old one).");
  process.exit(1);
}

const kp = Ed25519Keypair.generate();
const address = kp.toSuiAddress();
const secret = kp.getSecretKey(); // bech32 "suiprivkey1…" form

const body = `# Sui keypair for Seal (operator). KEEP SECRET. Gitignored (*.key).
# Generated by apps/operator/scripts/seal-keygen.ts
# Sui address (public, fund this): ${address}
SUI_SEAL_KEYPAIR=${secret}
`;
writeFileSync(OUT, body, { mode: 0o600 });
try {
  chmodSync(OUT, 0o600);
} catch {
  /* best effort on platforms without chmod */
}

console.log("=== Sui wallet generated ===");
console.log(`Sui address (PUBLIC — fund this):  ${address}`);
console.log(`Secret written to:                 ${OUT}  (0600, gitignored)`);
console.log("");
console.log("Next: copy the SUI_SEAL_KEYPAIR line from seal-wallet.key into your .env");
console.log("Fund the address above with a small amount of SUI (~0.5 SUI covers publish + allowlist).");
